[project]
name = "adk-agents-meetup-backend"
version = "0.1.0"
description = "Backend for ADK Agents Meetup"
dependencies = [
	"requests",
	"streamlit",
	"google-adk",
	"litellm"
]
requires-python = ">=3.12"